// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BoardHandle : RemoteTableHandle<EventContext, Board>
        {
            protected override string RemoteTableName => "board";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Board row) => row.Id;

                public IdUniqueIndex(BoardHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BoardHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Board row) => row.Id;
        }

        public readonly BoardHandle Board;
    }
}
