// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StrokeHandle : RemoteTableHandle<EventContext, Stroke>
        {
            protected override string RemoteTableName => "stroke";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Stroke row) => row.Id;

                public IdUniqueIndex(StrokeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StrokeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Stroke row) => row.Id;
        }

        public readonly StrokeHandle Stroke;
    }
}
