// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Stroke
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "board_id")]
        public ulong BoardId;
        [DataMember(Name = "user")]
        public string User;
        [DataMember(Name = "color")]
        public string Color;
        [DataMember(Name = "thickness")]
        public float Thickness;
        [DataMember(Name = "points")]
        public System.Collections.Generic.List<Point> Points;
        [DataMember(Name = "timestamp")]
        public SpacetimeDB.Timestamp Timestamp;

        public Stroke(
            ulong Id,
            ulong BoardId,
            string User,
            string Color,
            float Thickness,
            System.Collections.Generic.List<Point> Points,
            SpacetimeDB.Timestamp Timestamp
        )
        {
            this.Id = Id;
            this.BoardId = BoardId;
            this.User = User;
            this.Color = Color;
            this.Thickness = Thickness;
            this.Points = Points;
            this.Timestamp = Timestamp;
        }

        public Stroke()
        {
            this.User = "";
            this.Color = "";
            this.Points = new();
        }
    }
}
