// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::point_type::Point;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddStrokeArgs {
    pub board_id: u64,
    pub color: String,
    pub thickness: f32,
    pub points: Vec<Point>,
}

impl From<AddStrokeArgs> for super::Reducer {
    fn from(args: AddStrokeArgs) -> Self {
        Self::AddStroke {
            board_id: args.board_id,
            color: args.color,
            thickness: args.thickness,
            points: args.points,
        }
    }
}

impl __sdk::InModule for AddStrokeArgs {
    type Module = super::RemoteModule;
}

pub struct AddStrokeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_stroke`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_stroke {
    /// Request that the remote module invoke the reducer `add_stroke` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_stroke`] callbacks.
    fn add_stroke(
        &self,
        board_id: u64,
        color: String,
        thickness: f32,
        points: Vec<Point>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_stroke`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddStrokeCallbackId`] can be passed to [`Self::remove_on_add_stroke`]
    /// to cancel the callback.
    fn on_add_stroke(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &f32, &Vec<Point>)
            + Send
            + 'static,
    ) -> AddStrokeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_stroke`],
    /// causing it not to run in the future.
    fn remove_on_add_stroke(&self, callback: AddStrokeCallbackId);
}

impl add_stroke for super::RemoteReducers {
    fn add_stroke(
        &self,
        board_id: u64,
        color: String,
        thickness: f32,
        points: Vec<Point>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_stroke",
            AddStrokeArgs {
                board_id,
                color,
                thickness,
                points,
            },
        )
    }
    fn on_add_stroke(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &f32, &Vec<Point>)
            + Send
            + 'static,
    ) -> AddStrokeCallbackId {
        AddStrokeCallbackId(self.imp.on_reducer(
            "add_stroke",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddStroke {
                                    board_id,
                                    color,
                                    thickness,
                                    points,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, board_id, color, thickness, points)
            }),
        ))
    }
    fn remove_on_add_stroke(&self, callback: AddStrokeCallbackId) {
        self.imp.remove_on_reducer("add_stroke", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_stroke`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_stroke {
    /// Set the call-reducer flags for the reducer `add_stroke` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_stroke(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_stroke for super::SetReducerFlags {
    fn add_stroke(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_stroke", flags);
    }
}
