// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearBoardArgs {
    pub board_id: u64,
}

impl From<ClearBoardArgs> for super::Reducer {
    fn from(args: ClearBoardArgs) -> Self {
        Self::ClearBoard {
            board_id: args.board_id,
        }
    }
}

impl __sdk::InModule for ClearBoardArgs {
    type Module = super::RemoteModule;
}

pub struct ClearBoardCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_board`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_board {
    /// Request that the remote module invoke the reducer `clear_board` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_clear_board`] callbacks.
    fn clear_board(&self, board_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `clear_board`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClearBoardCallbackId`] can be passed to [`Self::remove_on_clear_board`]
    /// to cancel the callback.
    fn on_clear_board(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> ClearBoardCallbackId;
    /// Cancel a callback previously registered by [`Self::on_clear_board`],
    /// causing it not to run in the future.
    fn remove_on_clear_board(&self, callback: ClearBoardCallbackId);
}

impl clear_board for super::RemoteReducers {
    fn clear_board(&self, board_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("clear_board", ClearBoardArgs { board_id })
    }
    fn on_clear_board(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> ClearBoardCallbackId {
        ClearBoardCallbackId(self.imp.on_reducer(
            "clear_board",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClearBoard { board_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, board_id)
            }),
        ))
    }
    fn remove_on_clear_board(&self, callback: ClearBoardCallbackId) {
        self.imp.remove_on_reducer("clear_board", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `clear_board`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_clear_board {
    /// Set the call-reducer flags for the reducer `clear_board` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn clear_board(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_clear_board for super::SetReducerFlags {
    fn clear_board(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("clear_board", flags);
    }
}
