// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateBoardArgs {
    pub name: String,
}

impl From<CreateBoardArgs> for super::Reducer {
    fn from(args: CreateBoardArgs) -> Self {
        Self::CreateBoard { name: args.name }
    }
}

impl __sdk::InModule for CreateBoardArgs {
    type Module = super::RemoteModule;
}

pub struct CreateBoardCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_board`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_board {
    /// Request that the remote module invoke the reducer `create_board` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_board`] callbacks.
    fn create_board(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_board`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateBoardCallbackId`] can be passed to [`Self::remove_on_create_board`]
    /// to cancel the callback.
    fn on_create_board(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateBoardCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_board`],
    /// causing it not to run in the future.
    fn remove_on_create_board(&self, callback: CreateBoardCallbackId);
}

impl create_board for super::RemoteReducers {
    fn create_board(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_board", CreateBoardArgs { name })
    }
    fn on_create_board(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateBoardCallbackId {
        CreateBoardCallbackId(self.imp.on_reducer(
            "create_board",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateBoard { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_create_board(&self, callback: CreateBoardCallbackId) {
        self.imp.remove_on_reducer("create_board", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_board`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_board {
    /// Set the call-reducer flags for the reducer `create_board` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_board(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_board for super::SetReducerFlags {
    fn create_board(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_board", flags);
    }
}
