// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteStrokeArgs {
    pub stroke_id: u64,
}

impl From<DeleteStrokeArgs> for super::Reducer {
    fn from(args: DeleteStrokeArgs) -> Self {
        Self::DeleteStroke {
            stroke_id: args.stroke_id,
        }
    }
}

impl __sdk::InModule for DeleteStrokeArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteStrokeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_stroke`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_stroke {
    /// Request that the remote module invoke the reducer `delete_stroke` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_stroke`] callbacks.
    fn delete_stroke(&self, stroke_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_stroke`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteStrokeCallbackId`] can be passed to [`Self::remove_on_delete_stroke`]
    /// to cancel the callback.
    fn on_delete_stroke(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteStrokeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_stroke`],
    /// causing it not to run in the future.
    fn remove_on_delete_stroke(&self, callback: DeleteStrokeCallbackId);
}

impl delete_stroke for super::RemoteReducers {
    fn delete_stroke(&self, stroke_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("delete_stroke", DeleteStrokeArgs { stroke_id })
    }
    fn on_delete_stroke(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteStrokeCallbackId {
        DeleteStrokeCallbackId(self.imp.on_reducer(
            "delete_stroke",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteStroke { stroke_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, stroke_id)
            }),
        ))
    }
    fn remove_on_delete_stroke(&self, callback: DeleteStrokeCallbackId) {
        self.imp.remove_on_reducer("delete_stroke", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_stroke`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_stroke {
    /// Set the call-reducer flags for the reducer `delete_stroke` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_stroke(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_stroke for super::SetReducerFlags {
    fn delete_stroke(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_stroke", flags);
    }
}
