// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::point_type::Point;
use super::stroke_type::Stroke;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stroke`.
///
/// Obtain a handle from the [`StrokeTableAccess::stroke`] method on [`super::RemoteTables`],
/// like `ctx.db.stroke()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stroke().on_insert(...)`.
pub struct StrokeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Stroke>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stroke`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StrokeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StrokeTableHandle`], which mediates access to the table `stroke`.
    fn stroke(&self) -> StrokeTableHandle<'_>;
}

impl StrokeTableAccess for super::RemoteTables {
    fn stroke(&self) -> StrokeTableHandle<'_> {
        StrokeTableHandle {
            imp: self.imp.get_table::<Stroke>("stroke"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StrokeInsertCallbackId(__sdk::CallbackId);
pub struct StrokeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StrokeTableHandle<'ctx> {
    type Row = Stroke;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Stroke> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StrokeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StrokeInsertCallbackId {
        StrokeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StrokeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StrokeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StrokeDeleteCallbackId {
        StrokeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StrokeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Stroke>("stroke");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct StrokeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StrokeTableHandle<'ctx> {
    type UpdateCallbackId = StrokeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StrokeUpdateCallbackId {
        StrokeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StrokeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Stroke>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Stroke>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `stroke`,
/// which allows point queries on the field of the same name
/// via the [`StrokeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stroke().id().find(...)`.
pub struct StrokeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Stroke, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StrokeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `stroke`.
    pub fn id(&self) -> StrokeIdUnique<'ctx> {
        StrokeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StrokeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Stroke> {
        self.imp.find(col_val)
    }
}
