// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddStrokeHandler(ReducerEventContext ctx, ulong boardId, string color, float thickness, System.Collections.Generic.List<Point> points);
        public event AddStrokeHandler? OnAddStroke;

        public void AddStroke(ulong boardId, string color, float thickness, System.Collections.Generic.List<Point> points)
        {
            conn.InternalCallReducer(new Reducer.AddStroke(boardId, color, thickness, points), this.SetCallReducerFlags.AddStrokeFlags);
        }

        public bool InvokeAddStroke(ReducerEventContext ctx, Reducer.AddStroke args)
        {
            if (OnAddStroke == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddStroke(
                ctx,
                args.BoardId,
                args.Color,
                args.Thickness,
                args.Points
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddStroke : Reducer, IReducerArgs
        {
            [DataMember(Name = "board_id")]
            public ulong BoardId;
            [DataMember(Name = "color")]
            public string Color;
            [DataMember(Name = "thickness")]
            public float Thickness;
            [DataMember(Name = "points")]
            public System.Collections.Generic.List<Point> Points;

            public AddStroke(
                ulong BoardId,
                string Color,
                float Thickness,
                System.Collections.Generic.List<Point> Points
            )
            {
                this.BoardId = BoardId;
                this.Color = Color;
                this.Thickness = Thickness;
                this.Points = Points;
            }

            public AddStroke()
            {
                this.Color = "";
                this.Points = new();
            }

            string IReducerArgs.ReducerName => "add_stroke";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddStrokeFlags;
        public void AddStroke(CallReducerFlags flags) => AddStrokeFlags = flags;
    }
}
