// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearBoardHandler(ReducerEventContext ctx, ulong boardId);
        public event ClearBoardHandler? OnClearBoard;

        public void ClearBoard(ulong boardId)
        {
            conn.InternalCallReducer(new Reducer.ClearBoard(boardId), this.SetCallReducerFlags.ClearBoardFlags);
        }

        public bool InvokeClearBoard(ReducerEventContext ctx, Reducer.ClearBoard args)
        {
            if (OnClearBoard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearBoard(
                ctx,
                args.BoardId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearBoard : Reducer, IReducerArgs
        {
            [DataMember(Name = "board_id")]
            public ulong BoardId;

            public ClearBoard(ulong BoardId)
            {
                this.BoardId = BoardId;
            }

            public ClearBoard()
            {
            }

            string IReducerArgs.ReducerName => "clear_board";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearBoardFlags;
        public void ClearBoard(CallReducerFlags flags) => ClearBoardFlags = flags;
    }
}
