// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateBoardHandler(ReducerEventContext ctx, string name);
        public event CreateBoardHandler? OnCreateBoard;

        public void CreateBoard(string name)
        {
            conn.InternalCallReducer(new Reducer.CreateBoard(name), this.SetCallReducerFlags.CreateBoardFlags);
        }

        public bool InvokeCreateBoard(ReducerEventContext ctx, Reducer.CreateBoard args)
        {
            if (OnCreateBoard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateBoard(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateBoard : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public CreateBoard(string Name)
            {
                this.Name = Name;
            }

            public CreateBoard()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "create_board";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateBoardFlags;
        public void CreateBoard(CallReducerFlags flags) => CreateBoardFlags = flags;
    }
}
