// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteStrokeAnyoneHandler(ReducerEventContext ctx, ulong strokeId);
        public event DeleteStrokeAnyoneHandler? OnDeleteStrokeAnyone;

        public void DeleteStrokeAnyone(ulong strokeId)
        {
            conn.InternalCallReducer(new Reducer.DeleteStrokeAnyone(strokeId), this.SetCallReducerFlags.DeleteStrokeAnyoneFlags);
        }

        public bool InvokeDeleteStrokeAnyone(ReducerEventContext ctx, Reducer.DeleteStrokeAnyone args)
        {
            if (OnDeleteStrokeAnyone == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteStrokeAnyone(
                ctx,
                args.StrokeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteStrokeAnyone : Reducer, IReducerArgs
        {
            [DataMember(Name = "stroke_id")]
            public ulong StrokeId;

            public DeleteStrokeAnyone(ulong StrokeId)
            {
                this.StrokeId = StrokeId;
            }

            public DeleteStrokeAnyone()
            {
            }

            string IReducerArgs.ReducerName => "delete_stroke_anyone";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteStrokeAnyoneFlags;
        public void DeleteStrokeAnyone(CallReducerFlags flags) => DeleteStrokeAnyoneFlags = flags;
    }
}
