// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteStrokeHandler(ReducerEventContext ctx, ulong strokeId);
        public event DeleteStrokeHandler? OnDeleteStroke;

        public void DeleteStroke(ulong strokeId)
        {
            conn.InternalCallReducer(new Reducer.DeleteStroke(strokeId), this.SetCallReducerFlags.DeleteStrokeFlags);
        }

        public bool InvokeDeleteStroke(ReducerEventContext ctx, Reducer.DeleteStroke args)
        {
            if (OnDeleteStroke == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteStroke(
                ctx,
                args.StrokeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteStroke : Reducer, IReducerArgs
        {
            [DataMember(Name = "stroke_id")]
            public ulong StrokeId;

            public DeleteStroke(ulong StrokeId)
            {
                this.StrokeId = StrokeId;
            }

            public DeleteStroke()
            {
            }

            string IReducerArgs.ReducerName => "delete_stroke";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteStrokeFlags;
        public void DeleteStroke(CallReducerFlags flags) => DeleteStrokeFlags = flags;
    }
}
